# Generated by Django 4.1.4 on 2023-02-02 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blood_bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=40)),
                ('dist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.district')),
            ],
            options={
                'db_table': 'blood_bank',
            },
        ),
    ]
